# Generated by Django 5.1.3 on 2024-12-15 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zzenplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='accessories/'),
            preserve_default=False,
        ),
    ]
